/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_m2049r_xmrwallet_model_WalletManager */

#ifndef _Included_com_m2049r_xmrwallet_model_WalletManager
#define _Included_com_m2049r_xmrwallet_model_WalletManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_m2049r_xmrwallet_model_WalletManager
 * Method:    createWallet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Lcom/m2049r/xmrwallet/model/Wallet;
 */
JNIEXPORT jobject JNICALL Java_com_m2049r_xmrwallet_model_WalletManager_createWallet
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_m2049r_xmrwallet_model_WalletManager
 * Method:    openWallet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/m2049r/xmrwallet/model/Wallet;
 */
JNIEXPORT jobject JNICALL Java_com_m2049r_xmrwallet_model_WalletManager_openWallet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_m2049r_xmrwallet_model_WalletManager
 * Method:    recoveryWallet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Lcom/m2049r/xmrwallet/model/Wallet;
 */
JNIEXPORT jobject JNICALL Java_com_m2049r_xmrwallet_model_WalletManager_recoveryWallet
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jlong);

/*
 * Class:     com_m2049r_xmrwallet_model_WalletManager
 * Method:    loadWallet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/m2049r/xmrwallet/model/Wallet;
 */
JNIEXPORT jobject JNICALL Java_com_m2049r_xmrwallet_model_WalletManager_loadWallet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_m2049r_xmrwallet_model_WalletManager
 * Method:    walletExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_m2049r_xmrwallet_model_WalletManager_walletExists
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
