/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_m2049r_xmrwallet_model_PendingTransaction */

#ifndef _Included_com_m2049r_xmrwallet_model_PendingTransaction
#define _Included_com_m2049r_xmrwallet_model_PendingTransaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_m2049r_xmrwallet_model_PendingTransaction
 * Method:    getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_m2049r_xmrwallet_model_PendingTransaction_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_PendingTransaction
 * Method:    getErrorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_m2049r_xmrwallet_model_PendingTransaction_getErrorString
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_PendingTransaction
 * Method:    commit
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_m2049r_xmrwallet_model_PendingTransaction_commit
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_m2049r_xmrwallet_model_PendingTransaction
 * Method:    getFirstTxId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_m2049r_xmrwallet_model_PendingTransaction_getFirstTxId
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_PendingTransaction
 * Method:    getFee
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_m2049r_xmrwallet_model_PendingTransaction_getFee
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_PendingTransaction
 * Method:    getSerializedTransaction
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_m2049r_xmrwallet_model_PendingTransaction_getSerializedTransaction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
