/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_m2049r_xmrwallet_model_Wallet */

#ifndef _Included_com_m2049r_xmrwallet_model_Wallet
#define _Included_com_m2049r_xmrwallet_model_Wallet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getBalance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getBalance
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getUnlockedBalance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getUnlockedBalance
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getSeed
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getSeed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getErrorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getErrorString
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    setDaemonAddress
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_m2049r_xmrwallet_model_Wallet_setDaemonAddress
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    setDaemonLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_m2049r_xmrwallet_model_Wallet_setDaemonLogin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getBlockChainHeight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getBlockChainHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    getDaemonBlockChainHeight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_m2049r_xmrwallet_model_Wallet_getDaemonBlockChainHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    refresh
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_m2049r_xmrwallet_model_Wallet_refresh
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    refreshHistory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_m2049r_xmrwallet_model_Wallet_refreshHistory
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    createTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;JII)Lcom/m2049r/xmrwallet/model/PendingTransaction;
 */
JNIEXPORT jobject JNICALL Java_com_m2049r_xmrwallet_model_Wallet_createTransactionJ
  (JNIEnv *, jobject, jstring, jstring, jlong, jint, jint, jint);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    submitTransaction
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_m2049r_xmrwallet_model_Wallet_submitTransaction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    store
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_m2049r_xmrwallet_model_Wallet_store
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_m2049r_xmrwallet_model_Wallet_close
  (JNIEnv *, jobject);

/*
 * Class:     com_m2049r_xmrwallet_model_Wallet
 * Method:    setListener
 * Signature: (Lcom/m2049r/xmrwallet/model/Wallet/Listener;)V
 */
JNIEXPORT void JNICALL Java_com_m2049r_xmrwallet_model_Wallet_setListener
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
